### ISSUE TITLE
Problem trying to edit book metadata

### ISSUE THREAD

**Issue by klevasseur** [RunestoneInteractive/rs#456]
I'm trying to load a book project onto Runestone and have run into a problem.  When I entered the metadata for the book, I hadn't realized that dashes were not allowed in the document ID, which I had set to "active-ads".   When I try to replace the ID value with "activeads" I get an "Internal Server Error".   Is there a way to get around this.  

[link to my metadata](https://author.runestone.academy/author/editlibrary/active-ads)

**Comment by bnmnetp** [comment]
Hmmm, I don't think I anticipated someone changing the document-id through this interface.... Maybe the simplest solution is for you to just create a new entry and I can delete the old one manually.

**Comment by klevasseur** [comment]
Ok, sounds good. Please delete active-ads any time.

Ken

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bnmnetp** [comment]
Done.

**Comment by klevasseur** [comment]
Bradley:

I added my project (activeads) back on Runestone , replicating my other project (ads) in its structure.  Although I have no reading assignments in it at this time, ads seems to be working ok.   However activeads is not loading properly  I can’t figure out why. Sorry to bother you about this.

When I added activeads the first time, may spell checker changed the id to actives, so I have that erroneous entry on the author page.


Ken Levasseur


From: Bradley Miller ***@***.***>
Date: Monday, January 1, 2024 at 12:34 PM
To: RunestoneInteractive/rs ***@***.***>
Cc: Levasseur, Kenneth ***@***.***>, Author ***@***.***>
Subject: Re: [RunestoneInteractive/rs] Problem trying to edit book metadata (Issue #456)
Done. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <RunestoneInteractive/rs/issues/456/1873412409@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/NcNAlj2UIVkjDA!6AAQY9UKnTLns6Yzu9xitZlhhXOgBhaN27KjYlFwuGiuOEr3vzbAu0jMjMoJhEueaTCtAOILjau8aBCNqzkfLk1SsKkRtgu1_4WqX9afq0gZD7FtbKl08Q$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/NcNAlj2UIVkjDA!6AAQY9UKnTLns6Yzu9xitZlhhXOgBhaN27KjYlFwuGiuOEr3vzbAu0jMjMoJhEueaTCtAOILjau8aBCNqzkfLk1SsKkRtgu1_4WqX9afq0gZD7FtbKl08Q$>


ZjQcmQRYFpfptBannerEnd

Done.

**Comment by bnmnetp** [comment]
You were missing some key files that Runestone activities need.  I have added them and pushed to all servers.

I see that you are using the new V2 project file syntax.  I still have some work to do to get my production scripts to work with V2 project files.

**Comment by klevasseur** [comment]
I see that you are using the new V2 project file syntax. I still have some work to do to get my production scripts to work with V2 project files

Do you recommend that I wait for previous version, or wait . I’m not in a hurry.

Ken Levasseur


From: Bradley Miller ***@***.***>
Date: Monday, January 8, 2024 at 5:28 PM
To: RunestoneInteractive/rs ***@***.***>
Cc: Levasseur, Kenneth ***@***.***>, Author ***@***.***>
Subject: Re: [RunestoneInteractive/rs] Problem trying to edit book metadata (Issue #456)
You were missing some key files that Runestone activities need. I have added them and pushed to all servers. I see that you are using the new V2 project file syntax. I still have some work to do to get my production scripts to work with V2
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/NcNAlj2UIVkjDA!6AAQY9UKnTLns6Yzu9xitZlhhXOgBhaN27KjYlFwuGiuOEr3vzbAuqiNLKpJ5Ioe2j1TDPOB1sXUrLMsi0UnOwU1IVd6AlIlYVPsAWPp-HjUvpTwxWWD8Q$>


ZjQcmQRYFpfptBannerEnd

You were missing some key files that Runestone activities need. I have added them and pushed to all servers.

I see that you are using the new V2 project file syntax. I still have some work to do to get my production scripts to work with V2 project files.
